#!/bin/bash
# ==============================
#   afl-fuzzer for bignum
# ==============================
# Usage:
#   sbatch tr1-afl-slurm folder_num runtime_seconds
# Example:
#      sbatch tr1-afl-slurm 5 60
#   Run afl-fuzz on HPC cluster for 60 seconds with the settings below. 
#   And, send output to "output/out5" folder
#

#SBATCH --constraint=AVX2
#SBATCH --time=24:10:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=1   # 1 processor core(s) per node
# #SBATCH --mail-user=username@email.com   # email address
# #SBATCH --mail-type=END
#SBATCH --output="out%x-%j.txt" # job standard output file (%j replaced by job id)
#SBATCH --error="err%x-%j.txt" # job standard error file (%j replaced by job id)


./afl-fuzz.sh $1 $2
