
# rewrite.sh 
#   this file is used to rewrite files generated by afl-fuzz adding 
#   file length to the end of file in binary format.


declare -a arr=("53"  "id:000003,src:000000,time:55,op:havoc,rep:8"
    "11"  "id:000004,src:000000,time:92,op:havoc,rep:4"
    "20"  "id:000005,src:000000,time:125,op:havoc,rep:8"
    "21"  "id:000006,src:000000,time:162,op:havoc,rep:2,+cov"
    "63"  "id:000007,src:000000,time:204,op:havoc,rep:8"
    "63"  "id:000007,src:000000,time:204,op:havoc,rep:82"
    "32"  "id:000008,src:000000,time:229,op:havoc,rep:16"
    "54"  "id:000009,src:000000,time:276,op:havoc,rep:8"
    "20"  "id:000010,src:000000,time:328,op:havoc,rep:16"
    "23"  "id:000011,src:000000,time:477,op:havoc,rep:8"
    "10"  "id:000012,src:000000,time:616,op:havoc,rep:16"
    "11"  "id:000013,src:000000,time:2542,op:havoc,rep:4"
    "18"  "id:000014,src:000000,time:3234,op:havoc,rep:4"
    "16"  "id:000015,src:000000,time:4193,op:havoc,rep:16"
    "10"  "id:000016,src:000000,time:4916,op:havoc,rep:16"
    "10"  "id:000017,src:000000,time:6596,op:havoc,rep:16"
    "10"  "id:000018,src:000000,time:7181,op:havoc,rep:16"
    "137" "id:000019,src:000012+000007,time:9695,op:splice,rep:16"
    "39"  "id:000020,src:000006,time:9790,op:havoc,rep:2"
    "163" "id:000021,src:000012+000019,time:10129,op:splice,rep:16"
    "265" "id:000022,src:000012+000021,time:13383,op:splice,rep:16"
    "262" "id:000023,src:000012+000022,time:14049,op:splice,rep:16"
    "259" "id:000024,src:000012+000022,time:14084,op:splice,rep:16"
    "257" "id:000025,src:000012+000022,time:14132,op:splice,rep:2"
    "258" "id:000026,src:000012+000022,time:14224,op:splice,rep:8"
    "1520" "id:000027,src:000006,time:600097,op:havoc,rep:64"
    "871" "id:000028,src:000006+000003,time:600553,op:splice,rep:64")

for (( i=0; i < 54; i+=2 ));
do

  ./rewrite "${arr[$i]}"  out/default/queue/${arr[$i+1]}

done

